development:
  client_id: your_client_id
  client_secret: your_client_secret
production:
  client_id: <%= Rails.application.credentials.dig(:google_auth, :client_id) %>
  client_secret: <%= Rails.application.credentials.dig(:google_auth, :client_secret) %>
test:
  client_id: test_client_id
  client_secret: test_client_secret
